services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chroma_data:/app/chroma_data
    environment:
      - DB_PORT=8000
  frontend:
    depends_on:
      - backend
    build: frontend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST_PORT=backend:8000
